[general]
enabled = yes
port = 5038
bindaddr = 127.0.0.1
displayconnects = yes
timestampevents = yes

[cardvalidator]
secret = <REDACTED_AMI_SECRET>
deny = 0.0.0.0/0
permit = 127.0.0.1/32
read = call,user,system
write = call,user,system,originate
