[general]
externaddr=158.180.30.45
localnet=10.0.0.0/255.255.255.0
udpbindaddr=0.0.0.0:5060
tcpenable=yes
tcpbindaddr=0.0.0.0:5060
srvlookup=yes
allowguest=no
alwaysauthreject=yes
disallow=all
allow=ulaw
allow=alaw
allow=telephone-event
defaultexpiry=120
minexpiry=60
maxexpiry=3600
registertimeout=60
registerattempts=0
sendrpid=pai
trustrpid=yes
directmedia=no
videosupport=no
qualify=no
nat=force_rport,comedia
rtpend=20000
rtpstart=10000
register => <SIGNALWIRE_USERNAME>:<REDACTED_SIGNALWIRE_SIP_PASSWORD>@asaph-d09cb67ac8b1.sip.signalwire.com:5060/clientivr

[signalwire]
type=peer
username=clientivr
secret=<REDACTED_SIGNALWIRE_SIP_PASSWORD>
defaultuser=clientivr
fromuser=clientivr
fromdomain=asaph-d09cb67ac8b1.sip.signalwire.com
realm=asaph-d09cb67ac8b1.sip.signalwire.com
host=asaph-d09cb67ac8b1.sip.signalwire.com
port=5060
context=public
insecure=port,invite
nat=force_rport,comedia
dtmfmode=rfc2833
directmedia=no
canreinvite=no
qualify=no
sendrpid=pai
trustrpid=yes
disallow=all
allow=ulaw
allow=alaw
allow=telephone-event
videosupport=no
